fix C compilation warning from gcc about /* inside of comment section.
./beremiz/iec_std_lib.h:240:1: error: "/*" within comment [-Werror=comment]
 /*
 ^
compilation terminated due to -Wfatal-errors.
cc1: all warnings being treated as errors